# Creates a source-build tarball

jobs:
- job: Source_Build_Create_Tarball
  container: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-33-20210222183538-031e7d2
  displayName: Source-Build Create Tarball
  pool:
    vmImage: ubuntu-20.04
  variables:
    _BuildConfig: Release
  workspace:
    clean: all

  steps:
  - script: |
      set -x
      df -h

      officialBuildArgs=
      if [ '${{ and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}' = 'True' ]; then
        officialBuildArgs='/p:OfficialBuildId=$(BUILD.BUILDNUMBER)'
      fi

      ./build.sh \
        --ci \
        --configuration $(_BuildConfig) \
        --publish \
        -bl \
        $officialBuildArgs \
        /p:DotNetPublishUsingPipelines=true \
        /p:ArcadeBuildTarball=true
    displayName: Create Tarball

  - template: /src/SourceBuild/Arcade/eng/common/templates/steps/source-build-publish-logs.yml

  - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    # Check if the tarball should be built now so the result can be used in the build tarball job condition.
    # This prevents allocation of additional agents if the tarball build legs should be skipped.
    # Only build the tarball if the PR touches source-build source.
    - script: |
        if curl "https://api.github.com/repos/dotnet/installer/pulls/$(System.PullRequest.PullRequestNumber)/files" | grep '"filename": "src/SourceBuild/*'
        then
          echo "##vso[task.setvariable variable=_includeTarballBuild;isoutput=true]true"
        fi
      displayName: Tarball Build Check
      name: Tarball_Build_Check
