# Creates a source-build tarball

jobs:
- job: Source_Build_Create_Tarball
  container: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-33-20210222183538-031e7d2
  displayName: Source-Build Create Tarball
  pool:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      name: NetCorePublic-Pool
      queue: BuildPool.Ubuntu.1604.Amd64.Open
    ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      name: NetCoreInternal-Pool
      queue: BuildPool.Ubuntu.1604.Amd64
  variables:
    _BuildConfig: Release
  workspace:
    clean: all

  steps:
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - task: Bash@3
      displayName: Setup Private Feeds Credentials
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/common/SetupNugetSources.sh
        arguments: $(Build.SourcesDirectory)/NuGet.config $Token
      env:
        Token: $(dn-bot-dnceng-artifact-feeds-rw)
  - script: |
      set -x
      df -h

      officialBuildArgs=
      if [ '${{ and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}' = 'True' ]; then
        officialBuildArgs='/p:OfficialBuildId=$(BUILD.BUILDNUMBER)'
      fi

      # If building on the internal project, the internal storage variable may be available (usually only if needed)
      # In that case, add variables to allow the download of internal runtimes if the specified versions are not found
      # in the default public locations.
      internalRuntimeDownloadArgs=
      if [ '$(dotnetclimsrc-read-sas-token-base64)' != '$''(dotnetclimsrc-read-sas-token-base64)' ]; then
        internalRuntimeDownloadArgs='/p:DotNetRuntimeSourceFeed=https://dotnetclimsrc.blob.core.windows.net/dotnet /p:DotNetRuntimeSourceFeedKey=$(dotnetclimsrc-read-sas-token-base64) --runtimesourcefeed https://dotnetclimsrc.blob.core.windows.net/dotnet --runtimesourcefeedkey $(dotnetclimsrc-read-sas-token-base64)'
      fi

      ./build.sh \
        --ci \
        --configuration $(_BuildConfig) \
        --publish \
        -bl \
        $officialBuildArgs \
        $internalRuntimeDownloadArgs \
        /p:DotNetPublishUsingPipelines=true \
        /p:ArcadeBuildTarball=true
    displayName: Create Tarball

  - template: /src/SourceBuild/Arcade/eng/common/templates/steps/source-build-publish-logs.yml

  - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    # Check if the tarball should be built now so the result can be used in the build tarball job condition.
    # This prevents allocation of additional agents if the tarball build legs should be skipped.
    # Only build the tarball if the PR touches source-build source.
    - script: |
        if curl "https://api.github.com/repos/dotnet/installer/pulls/$(System.PullRequest.PullRequestNumber)/files" | grep '"filename": "src/SourceBuild/*\|"filename": "eng/SourceBuild.Version.Details.xml"'
        then
          echo "##vso[task.setvariable variable=_includeTarballBuild;isoutput=true]true"
        fi
      displayName: Tarball Build Check
      name: Tarball_Build_Check
