# Builds a source-build tarball

parameters:
  # Custom condition to apply to the job
  condition: true

  # Dependent jobs that must be completed before this job will run
  dependsOn:

  # The resource id of the tarball to download and build
  tarballResourceId: current

  # The following parameters aren't expected to be passed in rather they are used for encapsulation
  # -----------------------------------------------------------------------------------------------
  fedora33Container: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-33-20210222183538-031e7d2
  poolInternal:
    name: NetCore1ESPool-Svc-Internal
    demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
  poolPublic:
    name: NetCore1ESPool-Svc-Public
    demands: ImageOverride -equals Build.Ubuntu.1804.Amd64.Open
  tarballDir: $(Build.StagingDirectory)/tarball

jobs:
- job: Build_Tarball
  condition: ${{ parameters.condition }}
  displayName: Build Tarball
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      ${{ parameters.poolPublic }}
    ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      ${{ parameters.poolInternal }}
  strategy:
    matrix:
      Fedora33-Online:
        _BuildArch: x64
        _Container: ${{ parameters.fedora33Container }}
        _RunOnline: true
      # Offline builds have prebuilts: https://github.com/dotnet/fsharp/issues/12499
      ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
        Fedora33-Offline:
          _BuildArch: x64
          _Container: ${{ parameters.fedora33Container }}
          _RunOnline: false
  timeoutInMinutes: 240
  workspace:
    clean: all

  steps:
  - checkout: none

  - template: /src/SourceBuild/Arcade/eng/common/templates/steps/source-build-build-tarball.yml
    parameters:
      buildArch: $(_BuildArch)
      container: $(_Container)
      prepScript: |
        set -x

        docker run --rm -v ${{ parameters.tarballDir }}:/tarball -w /tarball $(_Container) ./prep.sh
      runOnline: $(_RunOnline)
      tarballDir: ${{ parameters.tarballDir }}
      tarballResourceId: ${{ parameters.tarballResourceId }}

- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - job: Rebuild_Tarball
    displayName: Rebuild Tarball With Previous
    dependsOn: Build_Tarball
    pool:
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        ${{ parameters.poolPublic }}
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        ${{ parameters.poolInternal }}
    strategy:
      matrix:
        Fedora33-Offline:
          _PreviousSourceBuildArtifact: Build Tarball Fedora33-Offline_Artifacts
          _BuildArch: x64
          _Container: ${{ parameters.fedora33Container }}
          _RunOnline: false
    timeoutInMinutes: 180
    workspace:
      clean: all

    steps:
    - checkout: none

    - download: current
      artifact: $(_PreviousSourceBuildArtifact)
      patterns: '*.tar.gz'
      displayName: Download Previous Source Build Artifacts

    - task: CopyFiles@2
      displayName: Copy Previous Source Build Artifacts
      inputs:
        SourceFolder: $(PIPELINE.WORKSPACE)/$(_PreviousSourceBuildArtifact)
        Contents: '*.tar.gz'
        TargetFolder: ${{ parameters.tarballDir }}/packages/archive/

    - template: /src/SourceBuild/Arcade/eng/common/templates/steps/source-build-build-tarball.yml
      parameters:
        additionalBuildArgs: --with-sdk /tarball/.dotnet
        buildArch: $(_BuildArch)
        container: $(_Container)
        prepScript: |
          set -x

          mkdir ${{ parameters.tarballDir }}/.dotnet
          tarballFilePath="${{ parameters.tarballDir }}/packages/archive/dotnet-sdk-*.tar.gz"
          eval tar -ozxf "$tarballFilePath" -C "${{ parameters.tarballDir }}/.dotnet"
          eval rm -f "$tarballFilePath"
        runOnline: $(_RunOnline)
        tarballDir: ${{ parameters.tarballDir }}
        tarballResourceId: ${{ parameters.tarballResourceId }}
