# Builds a source-build tarball

parameters:
  # Dependent jobs that must be completed before this job will run
  dependsOn:

  # Resource id of the installer build to retrieve source/product tarball's from
  installerBuildResourceId: current

  # The following parameters aren't expected to be passed in rather they are used for encapsulation
  # -----------------------------------------------------------------------------------------------
  alpine317Container: mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17
  centOS7Container: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-source-build
  centOSStream9Container: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream9
  debian11Arm64Container: mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-arm64v8
  fedora38Container: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-38
  ubuntu1804Container: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04
  poolInternalAmd64:
    name: NetCore1ESPool-Svc-Internal
    demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
  poolInternalAmd64PR:
    name: NetCore1ESPool-Internal-XL
    demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
  poolInternalArm64:
    name: Docker-Linux-Arm-Internal
  poolPublicAmd64:
    name: NetCore-Public-XL
    demands: ImageOverride -equals Build.Ubuntu.1804.Amd64.Open

jobs:
- template: /src/SourceBuild/Arcade/eng/common/templates/job/source-build-build-tarball.yml
  parameters:
    architecture: x64
    dependsOn: ${{ parameters.dependsOn }}
    ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
      excludeSdkContentTests: true
    installerBuildResourceId: ${{ parameters.installerBuildResourceId }}
    matrix:
      Alpine317-Offline:
        _BootstrapPrep: true
        _Container: ${{ parameters.alpine317Container }}
        _ExcludeOmniSharpTests: true
        _OverrideDistroDisablingSha1: false
        _RunOnline: false
      CentOS7-Online:
        _BootstrapPrep: false
        _Container: ${{ parameters.centOS7Container }}
        _EnablePoison: false
        _ExcludeOmniSharpTests: true
        _OverrideDistroDisablingSha1: false
        _RunOnline: true
      CentOS7-Offline:
        _BootstrapPrep: false
        _Container: ${{ parameters.centOS7Container }}
        _EnablePoison: false
        _ExcludeOmniSharpTests: true
        _OverrideDistroDisablingSha1: false
        _RunOnline: false
      ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
        CentOSStream9-Offline:
          _BootstrapPrep: false
          _Container: ${{ parameters.centOSStream9Container }}
          _EnablePoison: false
          _ExcludeOmniSharpTests: false
          _OverrideDistroDisablingSha1: true
          _RunOnline: false
        Fedora38-Offline:
          _BootstrapPrep: false
          _Container: ${{ parameters.fedora38Container }}
          _EnablePoison: true
          _ExcludeOmniSharpTests: false
          _OverrideDistroDisablingSha1: false
          _RunOnline: false
        Ubuntu1804-Offline:
          _BootstrapPrep: false
          _Container: ${{ parameters.ubuntu1804Container }}
          _EnablePoison: false
          _ExcludeOmniSharpTests: false
          _OverrideDistroDisablingSha1: false
          _RunOnline: false
    name: Build_Tarball_x64
    pool:
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        ${{ parameters.poolPublicAmd64 }}
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        ${{ if in(variables['Build.Reason'], 'PullRequest') }}:
          ${{ parameters.poolInternalAmd64PR }}
        ${{ else }}:
          ${{ parameters.poolInternalAmd64 }}

- ${{ if and(eq(variables['System.TeamProject'], 'internal'), ne(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /src/SourceBuild/Arcade/eng/common/templates/job/source-build-build-tarball.yml
    parameters:
      architecture: arm64
      dependsOn: ${{ parameters.dependsOn }}
      installerBuildResourceId: ${{ parameters.installerBuildResourceId }}
      matrix:
        Debian11-Offline:
          _BootstrapPrep: true
          _Container: ${{ parameters.debian11Arm64Container }}
          _EnablePoison: false
          _ExcludeOmniSharpTests: false
          _OverrideDistroDisablingSha1: false
          _RunOnline: false
      name: Build_Tarball_arm64
      pool: ${{ parameters.poolInternalArm64 }}

- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: /src/SourceBuild/Arcade/eng/common/templates/job/source-build-build-tarball.yml
    parameters:
      architecture: x64
      # Always attempt to run the bootstrap leg (e.g. even when stage 1 tests fail) in order to get a complete accessment of the build status.
      # The bootstrap build will shortcut if the stage 1 build failed.
      condition: succeededOrFailed()
      dependsOn: Build_Tarball_x64
      excludeSdkContentTests: true
      installerBuildResourceId: ${{ parameters.installerBuildResourceId }}
      matrix:
        Fedora38-Offline:
          _PreviousSourceBuildArtifact: Build_Tarball_x64 Fedora38-Offline_Artifacts
          _Container: ${{ parameters.fedora38Container }}
          _EnablePoison: false
          _ExcludeOmniSharpTests: false
          _OverrideDistroDisablingSha1: false
          _RunOnline: false
      name: Build_Tarball_x64_Using_Previous
      pool:
        ${{ if eq(variables['System.TeamProject'], 'public') }}:
          ${{ parameters.poolPublicAmd64 }}
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          ${{ parameters.poolInternalAmd64 }}
      usePreviousArtifacts: true
