# This is the main build definition (PR+CI) for dotnet/dotnet-lite
# This pipeline is triggered by PRs targetting and pushes to main, release/*, and internal/release/* branches

trigger:
  batch: true
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main
    - release/*
    - internal/release/*

stages:
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: templates/stages/vmr-scan.yml

- template: /src/installer/eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    isBuiltFromVmr: true
