# This yml is used by these pipelines and triggers:
#
# - dotnet-source-build-lite (internal)
#   - PR: release/* and main, lite build
#   - CI: main only, every batched commit, lite build

trigger:
  batch: true
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main
    - release/*

stages:
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: templates/stages/vmr-scan.yml

- template: /src/installer/eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    isBuiltFromVmr: true
    isSourceOnlyBuild: true
    scope: lite
