# This is the dotnet/dotnet-lite pipeline that is triggered by all PRs and pushes to main.

trigger:
  batch: true
  branches:
    include:
    - main

pr:
  branches:
    include:
    - '*'

stages:
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: templates/stages/vmr-scan.yml

- template: /src/installer/eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    isBuiltFromVmr: true
    isFullBuild: false
