# This is the main build definition (PR+CI) for dotnet/dotnet

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - internal/release/*

pr:
  branches:
    include:
    - main
    - release/*
    - internal/release/*

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Internal
        image: 1es-windows-2022
        os: windows

      baseline:
        baselineFile: $(Build.SourcesDirectory)\.config\guardian\.gdnbaselines
    
    customBuildTags:
    - ES365AIMigrationTooling
    
    stages:
    - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      - template: /eng/pipelines/templates/stages/vmr-scan.yml@self
    - template: /src/installer/eng/pipelines/templates/stages/vmr-build.yml@self
      parameters:
        isBuiltFromVmr: true
