# This is the dotnet/dotnet pipeline that is triggered:
# - Full build every weekday at midnight PST (08:00 UTC) for "main"
# - Lite build for PRs and when changes are pushed to release/* and internal/release/* branches.

schedules:
- cron: '0 8 * * Mon-Fri'
  displayName: Weekday midnight build
  branches:
    include:
    - main
  batch: true

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - internal/release/*

pr:
  branches:
    include:
    - main
    - release/*

variables:
# enable source-only build for pipelines with the -source-build suffix
- name: isSourceOnlyBuild
  value: ${{ in(variables['Build.DefinitionName'], '-source-build') }}

stages:
- template: templates/stages/vmr-scan.yml

- template: /src/installer/eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    isBuiltFromVmr: true
    isLiteBuild: ${{ ne(variables['Build.Reason'], 'Schedule') }}
    isSourceOnlyBuild: ${{ variables.isSourceOnlyBuild }}
