# This is the dotnet/dotnet pipeline that is triggered every weekday at midnight (00:00 UTC) for "main" and when changes are pushed to all other branches.

schedules:
- cron: '0 0 * * Mon-Fri'
  displayName: Weekday midnight build
  branches:
    include:
    - main
  batch: true

trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude:
    - main

pr: none

stages:
- ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/main') }}:
  - template: templates/stages/vmr-scan.yml

- template: /src/installer/eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    isBuiltFromVmr: true
    isFullBuild: true
