# This is the dotnet/dotnet pipeline that is triggered every weekday at midnight (00:00 UTC) for "main" and when changes are pushed to release/* and internal/release/* branches.

schedules:
- cron: '0 0 * * Mon-Fri'
  displayName: Weekday midnight build
  branches:
    include:
    - main
  batch: true

trigger:
  batch: true
  branches:
   include:
   - release/*
   - internal/release/*

pr: none

stages:
- ${{ if ne(variables['Build.Reason'], 'Schedule') }}:
  - template: templates/stages/vmr-scan.yml

- template: /src/installer/eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    isBuiltFromVmr: true
    isLiteBuild: false
