# This is the main build definition (CI) for dotnet/dotnet
# This pipeline runs on a schedule every weekday at midnight (00:00 UTC) for "main" and when changes are pushed to "release/" and "internal/release/".

schedules:
- cron: '0 0 * * Mon-Fri'
  displayName: Weekday midnight build
  branches:
    include:
    - main
  batch: true

trigger:
  batch: true
  branches:
    include:
    - release/*
    - internal/release/*

stages:
- template: templates/stages/vmr-scan.yml

- template: /src/installer/eng/pipelines/templates/stages/vmr-build.yml
  parameters:
    isBuiltFromVmr: true
    