#
# See https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for details on this file.
#

schedules:
# Cron timezone is UTC.
- cron: "0 18 * * *"
  displayName: Run tests daily at 6 PM UTC (11 AM PT)
  branches:
    include:
    - main
  always: true

# Do not run in PR builds nor support other triggers.
pr: none
trigger: none

variables:
- name: _TeamName
  value: SDK

jobs:
- ${{ if and(ne(variables['System.TeamProject'], 'public'), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'Manual'))) }}:
  - template: /eng/common/templates/job/onelocbuild.yml
    parameters:
      CreatePr: ${{ ne(variables['Build.Reason'], 'Manual') }}
      LclPackageId: 'LCL-JUNO-PROD-DOTNETINSTALLER'
      LclSource: lclFilesFromPackage
      MirrorBranch: main
      MirrorRepo: installer