trigger: none
pr: none

resources:
  pipelines:
  - pipeline: installer-build-resource
    source: dotnet-installer-official-ci
    trigger:
      branches:
        include:
        - main
        - release/*
        - internal/release/*
        exclude:
        - release/6.0.3xx
        - internal/release/6.0.3xx
        - release/6.0.4xx
        - internal/release/6.0.4xx
      stages:
      - build
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Svc-Internal
        image: 1es-windows-2022
        os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: build
      jobs:
      - template: /src/SourceBuild/Arcade/eng/common/templates/job/source-build-run-tarball-build.yml@self
        parameters:
          installerBuildResourceId: installer-build-resource
