trigger: none
pr: none
resources:
  pipelines:
  - pipeline: installer-build-resource
    source: dotnet-installer-official-ci
    trigger: true # Run pipeline when any run of dotnet-installer-official-ci completes

stages:
- stage: build
  jobs:
  - template: /src/SourceBuild/Arcade/eng/common/templates/job/source-build-run-tarball-build.yml
    parameters:
      tarballResourceId: installer-build-resource
