trigger: none
pr: none
resources:
  pipelines:
  - pipeline: installer-build-resource
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      source: installer
    ${{ if ne(variables['System.TeamProject'], 'public') }}:
      source: dotnet-installer-official-ci
    trigger: true # Run pipeline when any run of installer CI completes

stages:
- stage: build
  jobs:
  - template: /src/SourceBuild/Arcade/eng/common/templates/job/source-build-run-tarball-build.yml
    parameters:
      tarballResourceId: installer-build-resource
