trigger: none
pr: none
resources:
  pipelines:
  - pipeline: installer-build-resource
    source: dotnet-installer-official-ci
    trigger:
      branches:
        include:
        - main
        - release/*
        - internal/release/*
        exclude:
        - release/7.0.2xx
        - internal/release/7.0.2xx
        - release/7.0.3xx
        - internal/release/7.0.3xx
        - release/7.0.4xx
        - internal/release/7.0.4xx
      stages:
      - build

stages:
- stage: build
  jobs:
  - template: /src/SourceBuild/Arcade/eng/common/templates/job/source-build-run-tarball-build.yml
    parameters:
      installerBuildResourceId: installer-build-resource
