trigger: none
pr: none
resources:
  pipelines:
  - pipeline: dotnet-installer-official-ci-resource
    source: dotnet-installer-official-ci
    trigger: true
  - pipeline: installer-resource
    source: installer
    trigger: true

stages:
- stage: build
  jobs:
  - template: /src/SourceBuild/Arcade/eng/common/templates/job/source-build-run-tarball-build.yml
    parameters:
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        tarballResourceId: installer-resource
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        tarballResourceId: dotnet-installer-official-ci-resource
