### This pipeline synchronizes code from product repositories into the VMR (https://github.com/dotnet/dotnet)

parameters:
- name: targetRef
  displayName: Target revision in dotnet/installer to synchronize
  type: string
  default: $(Build.SourceVersion)

- name: vmrBranch
  displayName: dotnet/dotnet branch to use
  type: string
  default: $(Build.SourceBranchName)

trigger:
  branches:
    include:
    - main

pr: none

resources:
  repositories:
  - repository: vmr
    type: github
    name: dotnet/dotnet
    endpoint: dotnet

variables:
- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  - group: DotNetBot-GitHub

- ${{ else }}:
  - name: BotAccount-dotnet-bot-repo-PAT
    value: N/A

jobs:
- template: ./pipelines/templates/jobs/vmr-synchronization.yml
  parameters:
    targetRef: ${{ parameters.targetRef }}
    vmrBranch: ${{ parameters.vmrBranch }}
    vmrToken: $(BotAccount-dotnet-bot-repo-PAT)
