### This pipeline validates new changes of the VMR (https://github.com/dotnet/dotnet)
### VMR is cloned and updates are applied locally

parameters:
- name: vmrBranch
  displayName: dotnet/dotnet branch to use
  type: string
  default: $(System.PullRequest.TargetBranch)

trigger: none

pr:
  branches:
    include:
    - main

resources:
  repositories:
  - repository: vmr
    type: github
    name: dotnet/dotnet
    endpoint: public

variables:
- template: /eng/common/templates/variables/pool-providers.yml

- name: vmrPath
  value: $(Agent.BuildDirectory)/vmr

- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  - group: DotNetBot-GitHub
- ${{ else }}:
  - name: BotAccount-dotnet-bot-repo-PAT
    value: N/A

jobs:
- job: Validate
  displayName: Test VMR synchronization
  timeoutInMinutes: 120

  pool:
    vmImage: ubuntu-latest

  steps:
  - template: ./pipelines/templates/steps/vmr-prepare.yml
    parameters:
      vmrBranch: ${{ parameters.vmrBranch }}

  - template: ./pipelines/templates/steps/vmr-pull-updates.yml
    parameters:
      vmrPath: $(vmrPath)
      vmrBranch: ${{ parameters.vmrBranch }}
      targetRef: $(Build.SourceVersion)
      vmrToken: $(BotAccount-dotnet-bot-repo-PAT)
