### This pipeline synchronizes code from product repositories into the VMR (https://github.com/dotnet/dotnet)

parameters:
- name: targetRef
  displayName: Target revision in dotnet/installer to synchronize to
  type: string
  default: $(Build.SourceVersion)

- name: vmrBranch
  displayName: dotnet/dotnet branch to use
  type: string
  default: $(Build.SourceBranchName)

- name: noPush
  displayName: Don't push changes to dotnet/dotnet
  type: boolean
  default: false

trigger:
  branches:
    include:
    - main
    - release/8.0.*
    - internal/release/8.0.*

pr: none

resources:
  repositories:
  - repository: vmr
    type: github
    name: dotnet/dotnet
    endpoint: dotnet

variables:
- name: vmrPath
  value: $(Agent.BuildDirectory)/vmr

- template: /eng/common/templates/variables/pool-providers.yml

- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  - group: DotNetBot-GitHub
- ${{ else }}:
  - name: BotAccount-dotnet-bot-repo-PAT
    value: N/A

jobs:
- job: Synchronize
  displayName: Synchronize dotnet/dotnet
  timeoutInMinutes: 120

  pool:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      name: $(DncEngPublicBuildPool)
      demands:
      - ImageOverride -equals Build.Ubuntu.2004.Amd64.Open
    ${{ else }}:
      name: $(DncEngInternalBuildPool)
      demands:
      - ImageOverride -equals Build.Ubuntu.2004.Amd64

  steps:
  - template: ./pipelines/templates/steps/vmr-prepare.yml
    parameters:
      vmrBranch: ${{ parameters.vmrBranch }}

  - template: ./pipelines/templates/steps/vmr-pull-updates.yml
    parameters:
      vmrPath: $(vmrPath)
      vmrToken: $(BotAccount-dotnet-bot-repo-PAT)
      targetRef: ${{ parameters.targetRef }}

  - ${{ if and(eq('${{ parameters.noPush }}', 'false'), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal')) }}:
    - script: |-
        set -x
        git config --global user.email 'dotnet-maestro[bot]@users.noreply.github.com' && git config --global user.name 'dotnet-maestro[bot]'
        git remote add dotnet 'https://$(BotAccount-dotnet-bot-repo-PAT)@github.com/dotnet/dotnet.git'
        git fetch dotnet
        git branch ${{ parameters.vmrBranch }}
        git branch --set-upstream-to=dotnet/${{ parameters.vmrBranch }} ${{ parameters.vmrBranch }} || echo 'Branch ${{ parameters.vmrBranch }} not found in remote'
        git push dotnet ${{ parameters.vmrBranch }}
      displayName: Push changes to dotnet/dotnet
      workingDirectory: $(vmrPath)
