trigger: none
pr: none
resources:
  pipelines:
  - pipeline: installer-build-resource
    source: dotnet-installer-official-ci
    trigger:
      branches:
        include:
        - main

  repositories:
  - repository: vmr
    type: github
    name: dotnet/dotnet
    endpoint: dotnet

stages:
- template: templates/stages/vmr-build.yml
  parameters:
    installerBuildResourceId: installer-build-resource
