### This pipeline validates new changes of the VMR (https://github.com/dotnet/dotnet)
### VMR is cloned and updates are applied locally

parameters:
- name: vmrBranch
  displayName: dotnet/dotnet branch to use
  type: string
  default: $(System.PullRequest.TargetBranch)

trigger: none

pr:
  branches:
    include:
    - main
    - release/*
    - internal/release/*

resources:
  repositories:
  - repository: vmr
    type: github
    name: dotnet/dotnet
    endpoint: public

variables:
- template: /eng/common/templates/variables/pool-providers.yml
- template: templates/variables/vmr-variables.yml

jobs:
- job: Validate
  displayName: Test VMR synchronization
  pool:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      name: $(DncEngPublicBuildPool)
      demands: ImageOverride -equals Build.Ubuntu.2004.Amd64.Open
    ${{ else }}:
      name: $(DncEngInternalBuildPool)
      demands: ImageOverride -equals Build.Ubuntu.2004.Amd64

  steps:
  - template: templates/steps/vmr-prepare.yml
    parameters:
      vmrBranch: ${{ parameters.vmrBranch }}

  - template: templates/steps/vmr-pull-updates.yml
    parameters:
      vmrPath: $(vmrPath)
      vmrBranch: ${{ parameters.vmrBranch }}
      targetRef: $(Build.SourceVersion)
      vmrToken: $(BotAccount-dotnet-bot-repo-PAT)
