pr: none

trigger:
  batch: true
  branches:
    include:
    - internal/release/*
    exclude:
    - internal/release/*.0.2xx
    - internal/release/*.0.3xx
    - internal/release/*.0.4xx

resources:
  repositories:
  - repository: vmr
    type: git
    name: dotnet-dotnet
    ref: $(Build.SourceBranch)

  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

parameters:
- name: vmrBranch
  displayName: dotnet-dotnet branch to push to
  type: string
  default: ' '

variables:
- template: /eng/common/templates-official/variables/pool-providers.yml@self

- ${{ if ne(parameters.vmrBranch, ' ') }}:
  - name: VmrBranch
    value: ${{ replace(parameters.vmrBranch, ' ', '') }}
- ${{ else }}:
  - name: VmrBranch
    value: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), 'refs/pull/', '') }}

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: $(DncEngInternalBuildPool)
      image: 1es-windows-2022-pt
      os: windows

    sdl:
      sourceRepositoriesToScan:
        exclude:
        - repository: vmr

    stages:
    - stage: VMRSynchronization
      displayName: VMR Synchronization
      jobs:
      - template: templates/jobs/vmr-synchronization.yml@self
        parameters:
          vmrBranch: ${{ variables.VmrBranch }}