### This pipeline validates new changes of the VMR (https://github.com/dotnet/dotnet)
### VMR is cloned and updates are applied locally

parameters:
- name: vmrBranch
  displayName: dotnet/dotnet branch to use
  type: string
  default: $(System.PullRequest.TargetBranch)

trigger: none

pr:
  branches:
    include:
    - main
    - release/*
    - internal/release/*

resources:
  repositories:
  - repository: vmr
    type: github
    name: dotnet/dotnet
    endpoint: public

variables:
- template: /eng/common/templates/variables/pool-providers.yml
- template: templates/variables/vmr-variables.yml
- ${{ if ne(variables['System.TeamProject'], 'public') }}:
  - group: AzureDevOps-Artifact-Feeds-Pats

jobs:
- job: Build_and_Test
  displayName: Build & Test / CentOSStream8-Online x64
  timeoutInMinutes: 300
  pool:
    ${{ if eq(variables['System.TeamProject'], 'public') }}:
      name: ${{ variables.poolPublicAmd64Name }}
      demands: ImageOverride -equals ${{ variables.poolPublicAmd64Image }}
    ${{ else }}:
      ${{ if in(variables['Build.Reason'], 'PullRequest') }}:
        name: ${{ variables.poolInternalAmd64PRName }}
        demands: ImageOverride -equals ${{ variables.poolInternalAmd64PRImage }}
      ${{ else }}:
        name: ${{ variables.poolInternalAmd64Name }}
        demands: ImageOverride -equals ${{ variables.poolInternalAmd64Image }}

  steps:
  - template: templates/steps/vmr-prepare.yml
    parameters:
      vmrBranch: ${{ parameters.vmrBranch }}

  - template: templates/steps/vmr-pull-updates.yml
    parameters:
      vmrPath: $(vmrPath)
      vmrBranch: ${{ parameters.vmrBranch }}
      targetRef: $(Build.SourceVersion)
      vmrToken: $(BotAccount-dotnet-bot-repo-PAT)

  - template: templates/steps/vmr-source-build.yml
    parameters:
      name: CentOSStream8-Online
      architecture: x64
      excludeSdkContentTests: true
      container: $(centOSStream8Container)
      installerBuildResourceId: current
      excludeOmniSharpTests: true
      runOnline: true
      bootstrapPrep: false
      enablePoison: false