trigger: none

jobs:
- template: ../../src/installer/src/SourceBuild/Arcade/eng/common/templates/job/source-build-build-tarball.yml
  parameters:
    architecture: x64
    excludeSdkContentTests: true
    matrix:
      Ubuntu1804-Offline:
        _BootstrapPrep: false
        _Container: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-20210924170306-047508b
        _EnablePoison: false
        _ExcludeOmniSharpTests: false
        _RunOnline: false
    name: Build_Tarball_x64
    pool:
      name: NetCore1ESPool-Svc-Internal
      demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
