### This stage builds https://github.com/dotnet/dotnet with varying parameters
### If run in a PR, new changes are applied to a local copy of the VMR, then it is built and tested

parameters:
  dependsOn: []
  condition: always()

  # Branch of the VMR to use (to push to for internal builds)
  vmrBranch: $(Build.SourceBranch)

  # True when the build is a lite build
  isLiteBuild: false

  # True when build is running from dotnet/dotnet directly
  isBuiltFromVmr: false

  # True when building the VMR in source-only mode
  isSourceOnlyBuild: false

#### SOURCE-ONLY BUILD ####
stages:
- ${{ if parameters.isSourceOnlyBuild }}:
  - stage: VMR_SourceOnly_Build
    displayName: VMR Source-Only Build
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    variables:
    - template: ../variables/vmr-stage.yml
    jobs:

    - template: ../jobs/vmr-build.yml
      parameters:
        # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
        buildName: CentOSStream8_Online_MsftSdk
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool:
          name: ${{ variables.defaultPoolName }}
          demands: ${{ variables.defaultPoolDemandsLinux }}
        container: ${{ variables.centOSStream8Container }}
        buildFromArchive: false            # 🚫
        buildSourceOnly: true              # ✅
        enablePoison: false                # 🚫
        excludeOmniSharpTests: true        # ✅
        runOnline: true                    # ✅
        useMonoRuntime: false              # 🚫
        withPreviousSDK: false             # 🚫

    ### Additional jobs for non-PR builds ###
    - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:

      - template: ../jobs/vmr-build.yml
        parameters:
          # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
          buildName: CentOSStream8_Online_CurrentSourceBuiltSdk
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          vmrBranch: ${{ variables.VmrBranch }}
          architecture: x64
          pool:
            name: ${{ variables.defaultPoolName }}
            demands: ${{ variables.defaultPoolDemandsLinux }}
          container: ${{ variables.centOSStream8Container }}
          buildFromArchive: false            # 🚫
          buildSourceOnly: true              # ✅
          enablePoison: false                # 🚫
          excludeOmniSharpTests: true        # ✅
          runOnline: true                    # ✅
          useMonoRuntime: false              # 🚫
          withPreviousSDK: false             # 🚫
          reuseBuildArtifactsFrom: CentOSStream8_Online_MsftSdk

      - template: ../jobs/vmr-build.yml
        parameters:
          # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
          buildName: Alpine319_Offline_PreviousSourceBuiltSdk
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          vmrBranch: ${{ variables.VmrBranch }}
          architecture: x64
          artifactsRid: alpine.3.19-x64
          pool:
            name: ${{ variables.defaultPoolName }}
            demands: ${{ variables.defaultPoolDemandsLinux }}
          container: ${{ variables.alpine319Container }}
          buildFromArchive: false            # 🚫
          buildSourceOnly: true              # ✅
          enablePoison: true                 # ✅
          excludeOmniSharpTests: true        # ✅
          runOnline: false                   # 🚫
          useMonoRuntime: false              # 🚫
          withPreviousSDK: true              # ✅

      ### Additional jobs for full build ###
      - ${{ if eq(parameters.isLiteBuild, false) }}:

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: Alpine319_Online_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.alpine319Container }}
            buildFromArchive: false            # 🚫
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: true        # ✅
            runOnline: true                    # ✅
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: CentOSStream8_Offline_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.centOSStream8Container }}
            buildFromArchive: true             # ✅
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: true        # ✅
            runOnline: false                   # 🚫
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: CentOSStream8_Online_PreviousSourceBuiltSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            artifactsRid: centos.8-x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.centOSStream8Container }}
            buildFromArchive: false            # 🚫
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: true        # ✅
            runOnline: true                    # ✅
            useMonoRuntime: false              # 🚫
            withPreviousSDK: true              # ✅

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: CentOSStream8_Offline_PreviousSourceBuiltSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            artifactsRid: centos.8-x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.centOSStream8Container }}
            buildFromArchive: false            # 🚫
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: true        # ✅
            runOnline: false                   # 🚫
            useMonoRuntime: false              # 🚫
            withPreviousSDK: true              # ✅

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: CentOSStream8_Mono_Offline_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.centOSStream8Container }}
            buildFromArchive: true             # ✅
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: true        # ✅
            runOnline: false                   # 🚫
            useMonoRuntime: true               # ✅
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: CentOSStream9_Offline_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.centOSStream9Container }}
            buildFromArchive: true             # ✅
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: false       # 🚫
            runOnline: false                   # 🚫
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: Fedora39_Offline_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.fedora39Container }}
            buildFromArchive: true             # ✅
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: false       # 🚫
            runOnline: false                   # 🚫
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: Ubuntu2204_Offline_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.ubuntu2204Container }}
            buildFromArchive: false            # 🚫
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: false       # 🚫
            runOnline: false                   # 🚫
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: Ubuntu2204Arm64_Offline_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: arm64
            pool: ${{ variables.defaultPoolNameLinuxArm64 }}
            container: ${{ variables.ubuntu2204ArmContainer }}
            buildFromArchive: false            # 🚫
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: false       # 🚫
            runOnline: false                   # 🚫
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: Fedora39_Offline_CurrentSourceBuiltSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.fedora39Container }}
            buildFromArchive: false            # 🚫
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: false       # 🚫
            runOnline: false                   # 🚫
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫
            reuseBuildArtifactsFrom: Fedora39_Offline_MsftSdk

#### VERTICAL BUILD ####
- ${{ if not(parameters.isSourceOnlyBuild) }}:
  - stage: VMR_Vertical_Build
    displayName: VMR Vertical Build
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    variables:
    - template: ../variables/vmr-stage.yml
    jobs:

    - template: ../jobs/vmr-build.yml
      parameters:
        buildName: MarinerCrossX64
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool:
          name: ${{ variables.defaultPoolName }}
          demands: ${{ variables.defaultPoolDemandsLinux }}
        container: ${{ variables.marinerX64CrossContainer }}
        excludeOmniSharpTests: true        # ✅
        crossRootFs: '/crossrootfs/x64'    # 📝
        targetRid: 'linux-x64'             # 📝

    ### Additional jobs for non-PR builds ###
    - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: OSXCrossX64
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          vmrBranch: ${{ variables.VmrBranch }}
          architecture: x64
          pool:
            vmImage: ${{ variables.defaultPoolNameMac }}
          container: ''
          excludeOmniSharpTests: true        # ✅
          targetRid: 'osx-x64'               # 📝

      - template: ../jobs/vmr-build.yml
        parameters:
          buildName: WindowsX64
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          vmrBranch: ${{ variables.VmrBranch }}
          architecture: x64
          pool:
            name: ${{ variables.defaultPoolName }}
            demands: ${{ variables.defaultPoolDemandsWindows }}
          container: ''
          excludeOmniSharpTests: true        # ✅
          targetRid: 'win-x64'               # 📝

      ### Additional jobs for full build ###
      - ${{ if eq(parameters.isLiteBuild, false) }}:

        - template: ../jobs/vmr-build.yml
          parameters:
            buildName: MarinerCrossArm64
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: arm64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.marinerArm64CrossContainer }}
            excludeOmniSharpTests: true        # ✅
            crossRootFs: '/crossrootfs/arm64'  # 📝
            targetRid: 'linux-arm64'           # 📝

        - template: ../jobs/vmr-build.yml
          parameters:
            buildName: OSXCrossArm64
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: arm64
            pool:
              vmImage: ${{ variables.defaultPoolNameMac }}
            container: ''
            excludeOmniSharpTests: true        # ✅
            useMonoRuntime: true               # ✅
            targetRid: 'osx-arm64'             # 📝