### This stage source-builds https://github.com/dotnet/dotnet with varying parameters
### If run in a PR, new changes are applied to a local copy of the VMR, then it is source-built and tested

parameters:
  dependsOn: []
  condition: always()

  # Branch of the VMR to use (to push to for internal builds)
  vmrBranch: $(Build.SourceBranch)

  # True when the build is a lite build
  isLiteBuild:

  # True when build is running from dotnet/dotnet directly
  isBuiltFromVmr:

  # The following parameters aren't expected to be passed in rather they are used for encapsulation
  # -----------------------------------------------------------------------------------------------
  marinerX64CrossContainer: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-amd64
  marinerArm64CrossContainer: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-arm64

  # Internal builds
  poolInternalAmd64:
    name: NetCore1ESPool-Svc-Internal
    demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
  poolInternalAmd64PR:
    name: NetCore1ESPool-Internal-XL
    demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
  poolInternalArm64:
    name: Docker-Linux-Arm-Internal

  # Public builds / PRs
  poolPublicAmd64:
    name: NetCore-Public-XL
    demands: ImageOverride -equals Build.Ubuntu.1804.Amd64.Open

  # Mac
  poolMac:
    vmImage: 'macos-12'

stages:
- stage: VMR_PoC_Build
  displayName: VMR PoC-Build
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  variables:
  - ${{ if eq(variables['System.TeamProject'], 'public') }}:
    - name: defaultPoolName
      value: ${{ parameters.poolPublicAmd64.name }}
    - name: defaultPoolDemands
      value: ${{ parameters.poolPublicAmd64.demands }}
  - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
    - ${{ if in(variables['Build.Reason'], 'PullRequest') }}:
      - name: defaultPoolName
        value: ${{ parameters.poolInternalAmd64PR.name }}
      - name: defaultPoolDemands
        value: ${{ parameters.poolInternalAmd64PR.demands }}
    - ${{ else }}:
      - name: defaultPoolName
        value: ${{ parameters.poolInternalAmd64.name }}
      - name: defaultPoolDemands
        value: ${{ parameters.poolInternalAmd64.demands }}

  - ${{ if ne(parameters.vmrBranch, '') }}:
    - name: VmrBranch
      value: ${{ parameters.vmrBranch }}
  - ${{ else }}:
    - name: VmrBranch
      value: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), 'refs/pull/', '') }}

  jobs:

  - template: ../jobs/vmr-build.yml
    parameters:
      # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
      buildName: MarinerCrossX64_Online_MsftSdk
      isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      vmrBranch: ${{ variables.VmrBranch }}
      architecture: x64
      pool:
        name: ${{ variables.defaultPoolName }}
        demands: ${{ variables.defaultPoolDemands }}
      container: ${{ parameters.marinerx64CrossContainer }}
      buildFromArchive: false            # 🚫
      enablePoison: false                # 🚫
      excludeOmniSharpTests: true        # ✅
      runOnline: true                    # ✅
      useMonoRuntime: true               # ✅
      withPreviousSDK: false             # 🚫
      crossRootFs: '/crossrootfs/x64'    # 📝
      runTests: false                    # 🚫
      targetOS: 'linux'                  # 📝
      targetArchitecture: 'x64'          # 📝

  - template: ../jobs/vmr-build.yml
    parameters:
      # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
      buildName: MarinerCrossArm64_Online_MsftSdk_Mono
      isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      vmrBranch: ${{ variables.VmrBranch }}
      architecture: arm64
      pool:
        name: ${{ variables.defaultPoolName }}
        demands: ${{ variables.defaultPoolDemands }}
      container: ${{ parameters.marinerArm64CrossContainer }}
      buildFromArchive: false            # 🚫
      enablePoison: false                # 🚫
      excludeOmniSharpTests: true        # ✅
      runOnline: true                    # ✅
      useMonoRuntime: true               # ✅
      withPreviousSDK: false             # 🚫
      crossRootFs: '/crossrootfs/arm64'  # 📝
      runTests: false                    # 🚫
      targetOS: 'linux'                  # 📝
      targetArchitecture: 'arm64'        # 📝

  - template: ../jobs/vmr-build.yml
    parameters:
      # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
      buildName: OSXCrossX64_Online_MsftSdk
      isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      vmrBranch: ${{ variables.VmrBranch }}
      architecture: x64
      pool:
        vmImage: ${{ parameters.poolMac.vmImage }}
      container: ''
      buildFromArchive: false            # 🚫
      enablePoison: false                # 🚫
      excludeOmniSharpTests: true        # ✅
      runOnline: true                    # ✅
      useMonoRuntime: true               # ✅
      withPreviousSDK: false             # 🚫
      runTests: false                    # 🚫
      targetOS: 'osx'                    # 📝
      targetArchitecture: 'x64'          # 📝

  - template: ../jobs/vmr-build.yml
    parameters:
      # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
      buildName: OSXCrossArm64_Online_MsftSdk
      isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      vmrBranch: ${{ variables.VmrBranch }}
      architecture: arm64
      pool:
        vmImage: ${{ parameters.poolMac.vmImage }}
      container: ''
      buildFromArchive: false            # 🚫
      enablePoison: false                # 🚫
      excludeOmniSharpTests: true        # ✅
      runOnline: true                    # ✅
      useMonoRuntime: true               # ✅
      withPreviousSDK: false             # 🚫
      runTests: false                    # 🚫
      targetOS: 'osx'                    # 📝
      targetArchitecture: 'arm64'        # 📝

  - template: ../jobs/vmr-build.yml
    parameters:
      # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
      buildName: MarinerCrossArm64_Online_MsftSdk_CoreCLR
      isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      vmrBranch: ${{ variables.VmrBranch }}
      architecture: arm64
      pool:
        name: ${{ variables.defaultPoolName }}
        demands: ${{ variables.defaultPoolDemands }}
      container: ${{ parameters.marinerArm64CrossContainer }}
      buildFromArchive: false            # 🚫
      enablePoison: false                # 🚫
      excludeOmniSharpTests: true        # ✅
      runOnline: true                    # ✅
      useMonoRuntime: false              # 🚫
      withPreviousSDK: false             # 🚫
      crossRootFs: '/crossrootfs/arm64'  # 📝
      runTests: false                    # 🚫
      targetOS: 'linux'                  # 📝
      targetArchitecture: 'arm64'        # 📝
