### This stage source-builds https://github.com/dotnet/dotnet with varying parameters
### If run in a PR, new changes are applied to a local copy of the VMR, then it is source-built and tested

parameters:
- name: dependsOn
  default: []
- name: condition
  default: always()

  # Branch of the VMR to use (to push to for internal builds)
- name: vmrBranch
  default: $(Build.SourceBranch)

  # True when build is running from dotnet/dotnet directly
- name: isBuiltFromVmr
  default: false

  # The following parameters aren't expected to be passed in rather they are used for encapsulation
  # -----------------------------------------------------------------------------------------------
- name: alpine317Container
  default: mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17
- name: centOSStream8Container
  default: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream8
- name: centOSStream9Container
  default: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream9
- name: fedora38Container
  default: mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-38
- name: ubuntu2204Container
  default: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04
- name: ubuntu2204ArmContainer
  default: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-arm64

# These are not expected to be passed it but rather just object variables reused below
- name: pool_Linux
  type: object
  default:
    name: $(defaultPoolName)
    image: $(poolImage_Linux)
    demands: ImageOverride -equals $(poolImage_Linux)
    os: linux

- name: pool_LinuxArm64
  type: object
  default:
    name: $(poolName_LinuxArm64)
    image: $(poolImage_LinuxArm64)
    demands: ImageOverride -equals $(poolImage_Linux)
    hostArchitecture: Arm64
    os: linux

stages:
- stage: VMR_Source_Build
  displayName: VMR Source-Build
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  variables:
  - template: /variables/vmr-build.yml@self
  - ${{ if ne(parameters.vmrBranch, '') }}:
    - name: VmrBranch
      value: ${{ parameters.vmrBranch }}
  - ${{ else }}:
    - name: VmrBranch
      value: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), 'refs/pull/', '') }}

  jobs:

  # PR and CI legs ------------------------------------

  - template: ../jobs/vmr-build.yml@self
    parameters:
      # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
      buildName: CentOSStream8_Online_MsftSdk
      isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      vmrBranch: ${{ variables.VmrBranch }}
      architecture: x64
      pool: ${{ variables.pool_Linux }}
      container: ${{ parameters.centOSStream8Container }}
      buildFromArchive: false            # 🚫
      enablePoison: false                # 🚫
      excludeOmniSharpTests: true        # ✅
      runOnline: true                    # ✅
      useMonoRuntime: false              # 🚫
      withPreviousSDK: false             # 🚫

  - template: ../jobs/vmr-build.yml@self
    parameters:
      # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
      buildName: CentOSStream8_Offline_MsftSdk
      isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      vmrBranch: ${{ variables.VmrBranch }}
      architecture: x64
      pool: ${{ variables.pool_Linux }}
      container: ${{ parameters.centOSStream8Container }}
      buildFromArchive: true             # ✅
      enablePoison: false                # 🚫
      excludeOmniSharpTests: true        # ✅
      runOnline: false                   # 🚫
      useMonoRuntime: false              # 🚫
      withPreviousSDK: false             # 🚫

  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:

    # CI - Stage 1 x64 legs ------------------------------------

    - template: ../jobs/vmr-build.yml@self
      parameters:
        # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
        buildName: Alpine317_Offline_MsftSdk
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool: ${{ variables.pool_Linux }}
        container: ${{ parameters.alpine317Container }}
        buildFromArchive: false            # ✅
        enablePoison: false                # 🚫
        excludeOmniSharpTests: true        # ✅
        runOnline: false                   # 🚫
        useMonoRuntime: false              # 🚫
        withPreviousSDK: false             # 🚫

    - template: ../jobs/vmr-build.yml@self
      parameters:
        # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
        buildName: CentOSStream8_Online_PreviousSourceBuiltSdk
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool: ${{ variables.pool_Linux }}
        container: ${{ parameters.centOSStream8Container }}
        buildFromArchive: false            # 🚫
        enablePoison: false                # 🚫
        excludeOmniSharpTests: true        # ✅
        runOnline: true                    # ✅
        useMonoRuntime: false              # 🚫
        withPreviousSDK: true              # ✅

    - template: ../jobs/vmr-build.yml@self
      parameters:
        # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
        buildName: CentOSStream8_Offline_PreviousSourceBuiltSdk
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool: ${{ variables.pool_Linux }}
        container: ${{ parameters.centOSStream8Container }}
        buildFromArchive: false            # 🚫
        enablePoison: false                # 🚫
        excludeOmniSharpTests: true        # ✅
        runOnline: false                   # 🚫
        useMonoRuntime: false              # 🚫
        withPreviousSDK: true              # ✅

    - template: ../jobs/vmr-build.yml@self
      parameters:
        # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
        buildName: CentOSStream8_Mono_Offline_MsftSdk
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool: ${{ variables.pool_Linux }}
        container: ${{ parameters.centOSStream8Container }}
        buildFromArchive: true             # ✅
        enablePoison: false                # 🚫
        excludeOmniSharpTests: true        # ✅
        runOnline: false                   # 🚫
        useMonoRuntime: true               # ✅
        withPreviousSDK: false             # 🚫

    - template: ../jobs/vmr-build.yml@self
      parameters:
        # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
        buildName: CentOSStream9_Offline_MsftSdk
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool: ${{ variables.pool_Linux }}
        container: ${{ parameters.centOSStream9Container }}
        buildFromArchive: true             # ✅
        enablePoison: false                # 🚫
        excludeOmniSharpTests: false       # 🚫
        runOnline: false                   # 🚫
        useMonoRuntime: false              # 🚫
        withPreviousSDK: false             # 🚫

    - template: ../jobs/vmr-build.yml@self
      parameters:
        # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
        buildName: Fedora38_Offline_MsftSdk
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool: ${{ variables.pool_Linux }}
        container: ${{ parameters.fedora38Container }}
        buildFromArchive: true             # ✅
        enablePoison: true                 # ✅
        excludeOmniSharpTests: false       # 🚫
        runOnline: false                   # 🚫
        useMonoRuntime: false              # 🚫
        withPreviousSDK: false             # 🚫

    - template: ../jobs/vmr-build.yml@self
      parameters:
        # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
        buildName: Ubuntu2204_Offline_MsftSdk
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool: ${{ variables.pool_Linux }}
        container: ${{ parameters.ubuntu2204Container }}
        buildFromArchive: false            # 🚫
        enablePoison: false                # 🚫
        excludeOmniSharpTests: false       # 🚫
        runOnline: false                   # 🚫
        useMonoRuntime: false              # 🚫
        withPreviousSDK: false             # 🚫

    # CI - Stage 1 arm64 Legs ------------------------------------

    - template: ../jobs/vmr-build.yml@self
      parameters:
        # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
        buildName: Ubuntu2204Arm64_Offline_MsftSdk
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: arm64
        pool: ${{ parameters.pool_LinuxArm64 }}
        container: ${{ parameters.ubuntu2204ArmContainer }}
        buildFromArchive: false            # 🚫
        enablePoison: false                # 🚫
        excludeOmniSharpTests: false       # 🚫
        runOnline: false                   # 🚫
        useMonoRuntime: false              # 🚫
        withPreviousSDK: false             # 🚫

    # CI - Stage 2 x64 Legs ------------------------------------

    - template: ../jobs/vmr-build.yml@self
      parameters:
        # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
        buildName: CentOSStream8_Online_CurrentSourceBuiltSdk
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool: ${{ variables.pool_Linux }}
        container: ${{ parameters.centOSStream8Container }}
        buildFromArchive: false            # 🚫
        enablePoison: false                # 🚫
        excludeOmniSharpTests: true        # ✅
        runOnline: false                   # 🚫
        useMonoRuntime: false              # 🚫
        withPreviousSDK: false             # 🚫
        reuseBuildArtifactsFrom: CentOSStream8_Online_MsftSdk

    - template: ../jobs/vmr-build.yml@self
      parameters:
        # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
        buildName: Fedora38_Offline_CurrentSourceBuiltSdk
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool: ${{ variables.pool_Linux }}
        container: ${{ parameters.fedora38Container }}
        buildFromArchive: false            # 🚫
        enablePoison: false                # 🚫
        excludeOmniSharpTests: false       # 🚫
        runOnline: false                   # 🚫
        useMonoRuntime: false              # 🚫
        withPreviousSDK: false             # 🚫
        reuseBuildArtifactsFrom: Fedora38_Offline_MsftSdk
