### This stage builds https://github.com/dotnet/dotnet with varying parameters
### If run in a PR, new changes are applied to a local copy of the VMR, then it is built and tested

parameters:
# Branch of the VMR to use (to push to for internal builds)
- name: vmrBranch
  type: string
  default: $(Build.SourceBranch)

# Scope of jobs which are executed
- name: scope
  type: string
  values:
  # run 1 leg for smoke tests
  - ultralite
  # run several legs e.g. win/linux/mac for basic testing
  - lite
  # run everything
  - full

# True when build is running from dotnet/dotnet directly
- name: isBuiltFromVmr
  type: boolean
  default: false

# True when building the VMR in source-only mode
- name: isSourceOnlyBuild
  type: boolean
  default: false

#### SOURCE-ONLY BUILD ####
stages:
- ${{ if parameters.isSourceOnlyBuild }}:
  - stage: VMR_SourceOnly_Build
    displayName: VMR Source-Only Build
    variables:
    - template: ../variables/vmr-stage.yml
      parameters:
        vmrBranch: ${{ parameters.vmrBranch }}
    jobs:

    ### Jobs for ultralite builds ###
    - template: ../jobs/vmr-build.yml
      parameters:
        # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
        buildName: CentOSStream8_Online_MsftSdk
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool:
          name: ${{ variables.defaultPoolName }}
          demands: ${{ variables.defaultPoolDemandsLinux }}
        container: ${{ variables.centOSStream8Container }}
        buildFromArchive: false            # 🚫
        buildSourceOnly: true              # ✅
        enablePoison: false                # 🚫
        excludeOmniSharpTests: true        # ✅
        runOnline: true                    # ✅
        runTests: true                     # ✅
        useMonoRuntime: false              # 🚫
        withPreviousSDK: false             # 🚫

    ### Additional jobs for lite/full builds ###
    - ${{ if in(parameters.scope, 'lite', 'full') }}:

      - template: ../jobs/vmr-build.yml
        parameters:
          # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
          buildName: CentOSStream8_Online_CurrentSourceBuiltSdk
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          vmrBranch: ${{ variables.VmrBranch }}
          architecture: x64
          pool:
            name: ${{ variables.defaultPoolName }}
            demands: ${{ variables.defaultPoolDemandsLinux }}
          container: ${{ variables.centOSStream8Container }}
          buildFromArchive: false            # 🚫
          buildSourceOnly: true              # ✅
          enablePoison: false                # 🚫
          excludeOmniSharpTests: true        # ✅
          runOnline: true                    # ✅
          runTests: true                     # ✅
          useMonoRuntime: false              # 🚫
          withPreviousSDK: false             # 🚫
          reuseBuildArtifactsFrom: CentOSStream8_Online_MsftSdk

      - template: ../jobs/vmr-build.yml
        parameters:
          # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
          buildName: Alpine319_Offline_PreviousSourceBuiltSdk
          isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
          vmrBranch: ${{ variables.VmrBranch }}
          architecture: x64
          artifactsRid: alpine.3.19-x64
          pool:
            name: ${{ variables.defaultPoolName }}
            demands: ${{ variables.defaultPoolDemandsLinux }}
          container: ${{ variables.alpine319Container }}
          buildFromArchive: false            # 🚫
          buildSourceOnly: true              # ✅
          enablePoison: true                 # ✅
          excludeOmniSharpTests: true        # ✅
          runOnline: false                   # 🚫
          runTests: true                     # ✅
          useMonoRuntime: false              # 🚫
          withPreviousSDK: true              # ✅

      ### Additional jobs for full build ###
      - ${{ if in(parameters.scope, 'full') }}:

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: Alpine319_Online_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.alpine319Container }}
            buildFromArchive: false            # 🚫
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: true        # ✅
            runOnline: true                    # ✅
            runTests: true                     # ✅
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: CentOSStream8_Offline_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.centOSStream8Container }}
            buildFromArchive: true             # ✅
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: true        # ✅
            runOnline: false                   # 🚫
            runTests: true                     # ✅
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: CentOSStream8_Online_PreviousSourceBuiltSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            artifactsRid: centos.8-x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.centOSStream8Container }}
            buildFromArchive: false            # 🚫
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: true        # ✅
            runOnline: true                    # ✅
            runTests: true                     # ✅
            useMonoRuntime: false              # 🚫
            withPreviousSDK: true              # ✅

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: CentOSStream8_Offline_PreviousSourceBuiltSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            artifactsRid: centos.8-x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.centOSStream8Container }}
            buildFromArchive: false            # 🚫
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: true        # ✅
            runOnline: false                   # 🚫
            runTests: true                     # ✅
            useMonoRuntime: false              # 🚫
            withPreviousSDK: true              # ✅

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: CentOSStream8_Mono_Offline_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.centOSStream8Container }}
            buildFromArchive: true             # ✅
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: true        # ✅
            runOnline: false                   # 🚫
            runTests: true                     # ✅
            useMonoRuntime: true               # ✅
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: CentOSStream9_Offline_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.centOSStream9Container }}
            buildFromArchive: true             # ✅
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: false       # 🚫
            runOnline: false                   # 🚫
            runTests: true                     # ✅
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: Fedora39_Offline_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.fedora39Container }}
            buildFromArchive: true             # ✅
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: false       # 🚫
            runOnline: false                   # 🚫
            runTests: true                     # ✅
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: Ubuntu2204_Offline_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.ubuntu2204Container }}
            buildFromArchive: false            # 🚫
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: false       # 🚫
            runOnline: false                   # 🚫
            runTests: true                     # ✅
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: Ubuntu2204Arm64_Offline_MsftSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: arm64
            pool: ${{ variables.defaultPoolNameLinuxArm64 }}
            container: ${{ variables.ubuntu2204ArmContainer }}
            buildFromArchive: false            # 🚫
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: false       # 🚫
            runOnline: false                   # 🚫
            runTests: true                     # ✅
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫

        - template: ../jobs/vmr-build.yml
          parameters:
            # Changing the build name requires updating the referenced name in the source-build-sdk-diff-tests.yml pipeline
            buildName: Fedora39_Offline_CurrentSourceBuiltSdk
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              name: ${{ variables.defaultPoolName }}
              demands: ${{ variables.defaultPoolDemandsLinux }}
            container: ${{ variables.fedora39Container }}
            buildFromArchive: false            # 🚫
            buildSourceOnly: true              # ✅
            enablePoison: false                # 🚫
            excludeOmniSharpTests: false       # 🚫
            runOnline: false                   # 🚫
            runTests: true                     # ✅
            useMonoRuntime: false              # 🚫
            withPreviousSDK: false             # 🚫
            reuseBuildArtifactsFrom: Fedora39_Offline_MsftSdk

#### VERTICAL BUILD ####
- ${{ if not(parameters.isSourceOnlyBuild) }}:
  - stage: VMR_Vertical_Build
    displayName: VMR Vertical Build
    variables:
    - template: ../variables/vmr-stage.yml
      parameters:
        vmrBranch: ${{ parameters.vmrBranch }}
    jobs:

    - template: ../jobs/vmr-build.yml
      parameters:
        buildName: Ubuntu2204
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool:
          name: ${{ variables.defaultPoolName }}
          demands: ${{ variables.defaultPoolDemandsLinux }}
        container: ${{ variables.ubuntu2204Container }}
        targetOS: linux
        targetArchitecture: x64

    - template: ../jobs/vmr-build.yml
      parameters:
        buildName: Windows
        isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
        vmrBranch: ${{ variables.VmrBranch }}
        architecture: x64
        pool:
          name: ${{ variables.defaultPoolName }}
          demands: ${{ variables.defaultPoolDemandsWindows }}
        container: ''
        targetOS: windows
        targetArchitecture: x64

    ### Additional jobs for full build ###
    - ${{ if in(parameters.scope, 'full') }}:

        - template: ../jobs/vmr-build.yml
          parameters:
            buildName: OSX
            isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
            vmrBranch: ${{ variables.VmrBranch }}
            architecture: x64
            pool:
              vmImage: ${{ variables.defaultPoolNameMac }}
            container: ''
            targetOS: osx
            targetArchitecture: x64

    # Cross builds are currently failing

      # - template: ../jobs/vmr-build.yml
      #   parameters:
      #     buildName: MarinerCross
      #     isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      #     vmrBranch: ${{ variables.VmrBranch }}
      #     architecture: x64
      #     pool:
      #       name: ${{ variables.defaultPoolName }}
      #       demands: ${{ variables.defaultPoolDemandsLinux }}
      #     container: ${{ variables.marinerX64CrossContainer }}
      #     crossRootFs: '/crossrootfs/x64'
      #     targetOS: linux
      #     targetArchitecture: x64

      # - template: ../jobs/vmr-build.yml
      #   parameters:
      #     buildName: MarinerCross
      #     isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      #     vmrBranch: ${{ variables.VmrBranch }}
      #     architecture: arm64
      #     pool:
      #       name: ${{ variables.defaultPoolName }}
      #       demands: ${{ variables.defaultPoolDemandsLinux }}
      #     container: ${{ variables.marinerArm64CrossContainer }}
      #     crossRootFs: '/crossrootfs/arm64'
      #     targetOS: linux
      #     targetArchitecture: arm64

      # - template: ../jobs/vmr-build.yml
      #   parameters:
      #     buildName: OSXCross
      #     isBuiltFromVmr: ${{ parameters.isBuiltFromVmr }}
      #     vmrBranch: ${{ variables.VmrBranch }}
      #     architecture: arm64
      #     pool:
      #       vmImage: ${{ variables.defaultPoolNameMac }}
      #     container: ''
      #     targetOS: osx
      #     targetArchitecture: arm64
